### ISSUE TITLE
Multiple boolean fields not prefixed by is/has

### ISSUE THREAD

**Issue by MartinGuindon** [fivetran/dbt_shopify_source#10]
The following booleans are not named with an is/has prefix as per the naming convention. I'll work on a PR to fix these.

@fivetran-kristin let me know if you are good with the proposed names.

| model                   | current name            | proposed name          |
|-------------------------|-------------------------|------------------------|
| stg_shopify__order      | buyer_accepts_marketing | has_accepted_marketing |
|                         | taxes_included          | has_taxes_included     |
|                         | test                    | is_test_order          |
| stg_shopify__customer   | accepts_marketing       | has_accepted_marketing |
| stg_shopify__order_line | gift_card               | is_gift_card           |
|                         | requires_shipping       | is_requiring_shipping  |

**Comment by fivetran-kristin** [comment]
@MartinGuindon thanks for the suggestion! I've pushed these updates [here](https://github.com/fivetran/dbt_shopify_source/commit/4a0a6de817d0d468d547bbd29966dc7a686c3165), so don't worry about creating a PR.  

FYI - I'm in the process of reviewing all outstanding Shopify PRs and issues today. I'll release a new version of the packages once I'm done.

**Comment by MartinGuindon** [comment]
Awesome, thank you :)
