### ISSUE TITLE
BUG - Package runs unsuccessfully if merchant does not have refunds/order_adjustments

### ISSUE THREAD

**Issue by milo157** [fivetran/dbt_shopify_source#23]
**Are you a current Fivetran customer?** 
Yes

**Describe the bug**
If a Shopify merchant has not issued any refunds or done any order adjustments then the following tables do no exist in your data warehouse:

- order_adjustment
- order_line_refund
- refund 

**Steps to reproduce**
In order to reproduce you would need to find a Shopify merchant that has not refunded a client. This will not create the tables mentioned above in your Data Warehouse and therefore when you execute this package it will return errors that some models could not be created because tables to not exist.

**Expected behavior**
This packages is expected to cater for this scenario so that the package may run successfully.

**Package Version**
[">=0.4.0","<0.5.0"]

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ x] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this issue @milo157! I apologize for the delayed response. This is a feature our team can integrate into the next release of the package. 

We will be able to add this task to our next sprint which starts mid next week. I will post back here with updates.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @milo157 I was able to get to this request and have working branches and corresponding PRs opened that implement this fix. Would you be able to give the working branches a run and see if this resolves your error? You can use the below config in your `packages.yml`
```yml
packages:
    - git: https://github.com/fivetran/dbt_shopify.git
      revision: feature/deactivate-refunds
      warn-unpinned: false
```
You can then add the below variables to your `dbt_project.yml` to deactivate the order adjustment and refund models.
```yml
vars:
    shopify__using_order_adjustment:  false  # true by default
    shopify__using_order_line_refund: false  # true by default
    shopify__using_order_refund:      false  # true by default
```
Let me know how it goes!

**Comment by fivetran-joemarkiewicz** [comment]
@milo157 just wanted to give an update that we have been able to release the latest version of the source package which accommodates the deactivation of these tables. I also have merged an accompanying change into the [dbt_shopify](https://github.com/fivetran/dbt_shopify) package which will allow you to run the package with these models disabled successfully!

As it is currently the end of the day, I will wait to cut the official release until Monday morning. In the meantime you are welcome to use the below `packages.yml` config to use and I will post back here once the update is officially live on the dbt hub.
```yml
packages:
    - git: https://github.com/fivetran/dbt_shopify.git
      warn-unpinned: false
```

**Comment by fivetran-joemarkiewicz** [comment]
FYI the release of the latest version of this package `v0.5.1` has just been cut and will be live on the [dbt hub](https://hub.getdbt.com/fivetran/shopify/latest/) and available for use at the top of the hour!

Please feel free to open another issue if you have any other questions or would like to discuss any future considerations for this package.

**Comment by milo157** [comment]
@fivetran-joemarkiewicz Sorry for my delayed reply and awesome that you got this out and working!

However, can I asked why you opted to go for the deactivation of tables rather than checking if tables exist and if not creating an empty version of them?

The use case I am referring to is a company that has not done a refund via Shopify however at a later stage does it. Therefore when the data warehouse syncs new rows, it doesn't require changing the DBT config but rather just the rows getting updated

**Comment by fivetran-joemarkiewicz** [comment]
Hi @milo157 that is a great question!

We opted for the deactivation as dbt does not have great functionality for checking if a source table exists at a dynamic level. We have been able to be a bit "hacky" in the past where if a source table does not exist then the dbt package will create a table with `null` records. However, this has typically raised more questions in the past and we try to avoid it when possible.

If there is a better option that you have used in the past leveraging dbt to check if a table exists (and it works across the major warehouses) then I would absolutely love to know as this is a situation we encounter frequently and would love to take a more nuanced approach moving forward. In the meantime, we plan to go the route of variable deactivation.

**Comment by milo157** [comment]
There are two routes you can follow in this scenario:

1. Creating a null table that you join on - very dependant on the scenario as you said
2. Not referring to the table in your final model if it does not exist so it caters for future changes that the data might be available at a later stage

The below has worked for me in the past, not sure if this what you tried to implement?

{%- set source_relation = adapter.get_relation(
      database=source('xxx', 'order_refunds__refund_line_items').database,
      schema=source('xxx', 'order_refunds__refund_line_items').schema,
      identifier=source('xx', 'order_refunds__refund_line_items').name) -%}

{% set table_exists=source_relation is not none   %}

{% if table_exists %}

**Refer to table that can potentially be undefined

{% else %}

**Do not refer to table that can potentially be undefined in your final model

{% endif %}

**Comment by fivetran-joemarkiewicz** [comment]
That actually is what we implemented in the past and have been able to see success! However I was running into issues with this implementation in this package as we leverage macros at the source level to allow for the unioning of source tables across schemas. 

I do like the idea of handling this issue with the above mentioned method rather than variable deactivation, but it would most likely require more time to build into our existing unioning macros. If you would like, I would encourage opening a new Issue highlighting this and our team can look to update this solution in a future sprint.
