### ISSUE TITLE
[Feature] Call out column names in staging models

### ISSUE THREAD

**Issue by fivetran-reneeli** [fivetran/dbt_shopify_source#34]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

- Update our package to make the columns explicit that we're selecting in the staging models, rather than select *.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-jamie** [comment]
this is in the new release!
