### ISSUE TITLE
[Feature] Readme update

### ISSUE THREAD

**Issue by fivetran-sheringuyen** [fivetran/dbt_shopify_source#37]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

This package needs a readme upgrade

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-jamie** [comment]
this is in the new release!
