### ISSUE TITLE
[Schema Change] <Shopify API Update 2022>

### ISSUE THREAD

**Issue by manhitv** [fivetran/dbt_shopify_source#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I have received information that Shopify has made some updates related to changing the schema of some tables, including the Shopify customers table (as shown in the figure below).

![unnamed](https://user-images.githubusercontent.com/49891103/211269850-7c03af99-8e5a-4833-9933-7b118f64e643.png)

I have checked the new ERD and found that the deprecated columns are still there and it does not affect the operation of the current **dbt_shopify**  too seriously. However, I want to update my data pipeline (using the **dbt_shopify** package) according to the latest updates, specifically update this mapping relation in **shopify_customer** table:

> email_marketing_consent_state --> has_accept_marketing

instead of

> accept_marketing -->has_accept_marketing
 
as I am seeing here https://github.com/ fivetran/dbt_shopify_source/blob/main/macros/staging_columns.sql.

### Expected behavior

Update this mapping relation in **shopify_customer** table:

> email_marketing_consent_state --> has_accept_marketing

instead of

> accept_marketing -->has_accept_marketing

### dbt Project configurations

name: 'fivetran_shopify'
version: '1.0.0'
config-version: 2

### Package versions

packages:
  - package: fivetran/shopify
    version: [">=0.6.0", "<0.7.0"]

### What database are you using dbt with?

bigquery

### dbt Version

None

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
hey there! so i am currently working on updates to the Shopify package that i believe capture what you're looking for. 

the mapping occurs on this branch [here](https://github.com/fivetran/dbt_shopify_source/blob/feature/revamp/documentation/models/stg_shopify__customer.sql#L45-L51) -- what do you think? @manhitv

**Comment by manhitv** [comment]
Oh thanks @fivetran-jamie. It looks like my problem will be solved immediately after the update but the output table schema will be changed a little (from _has_accept_marketing_ to _marketing_consent_state_), isn't it?
May I know when there is a new version so I can update? 
Thank you in advance.

**Comment by fivetran-jamie** [comment]
yes and yes! will ping you hear when it's live

**Comment by manhitv** [comment]
Thank you so much, @fivetran-jamie.
