### ISSUE TITLE
Consider adding passthrough columns

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_shopify_source#7]
In some instances, customers use multiple shopify connectors.  Our solution is to union all of the data together prior to running the transformation, however there may not be a way to differentiate the different connectors/shops.  Users would need to add an additional column to do this, and we would then need to allow customers to pass through these columns to the final models.

Related slack convo: https://getdbt.slack.com/archives/C0VLZPLAE/p1610571493343300

**Comment by MartinGuindon** [comment]
I'd be happy to work on this and contribute a PR as part of the project I'm working on. I think this should be pretty straightforward to implement. Here's the solution I'm thinking:

- introduce a configuration variable where a developer can set the name of one or more columns that are common to all tables, eg.:

```
vars:
    shopify_passthrough_columns: ["shop_identifier", "shop_url"]
```

- in each model, add a Jinja condition that checks if passthrough columns are defined in the project config, and if so, loop over them to add them in the select statement.

Any thoughts?

**Comment by fivetran-kristin** [comment]
@MartinGuindon that would be great!  A good example of how we've done this in the pass is in our salesforce model. 

Once you identify the models you'd like to include passthrough columns to, the steps include the following. I've linked examples of this work for each item.

Source package:
- Update dbt_project.yml file to include [passthrough variables](https://github.com/fivetran/dbt_salesforce_source/blob/master/dbt_project.yml#L20)
- Update staging models to utilize passthrough columns. Note this needs to be done in two places - [here](https://github.com/fivetran/dbt_salesforce_source/blob/master/models/stg_salesforce__account.sql#L25) and [here](https://github.com/fivetran/dbt_salesforce_source/blob/master/models/stg_salesforce__account.sql#L72).
[- Update README configuration to call out use of passthrough columns](https://github.com/fivetran/dbt_salesforce_source#configuration)

Transform package:
- Update dbt_project.yml file to include [passthrough columns](https://github.com/fivetran/dbt_salesforce/blob/master/dbt_project.yml#L23)
- Update any applicable models so that the passthrough columns flow through to final models.  Example of final model [here](https://github.com/fivetran/dbt_salesforce/blob/master/models/salesforce__opportunity_enhanced.sql#L51).
- Update [README](https://github.com/fivetran/dbt_salesforce#configuration)

**Comment by MartinGuindon** [comment]
Cool, pretty much the solution I had in mind, except with a per-model config which makes it even more flexible. 

I'm planning to work on this and issue a PR on the week of Jan. 25. :)
