### ISSUE TITLE
[Bug] stg_shopify__product_image unique combination_of_columns failing

### ISSUE THREAD

**Issue by ryan-brainforge** [fivetran/dbt_shopify_source#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The test is failing for me since my data has PRODUCT_IMAGE_ID's that have multiple PRODUCT_IDs. 
Can we add PRODUCT_IDs to the unique combination_of_columns test?

I'm using 2 schemas (unioning them)

### Relevant error log or model output

```shell
21:13:13  112 of 133 FAIL 33 dbt_utils_unique_combination_of_columns_stg_shopify__product_image_product_image_id__source_relation  [FAIL 33 in 1.10s]
```

### Expected behavior

Test should pass

### dbt Project configurations

vars:
 shopify_database: fivetran_database
 shopify_union_schemas: ['shopify','shopify_bt'] 

### Package versions

0.12.0

### What database are you using dbt with?

snowflake

### dbt Version

1.7.1

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-avinash** [comment]
Hi @ryan-brainforge , thanks for spotting this issue! I can confirm that our ERD does include `product_id` as a unique key in the `product_image` source table. So agreed that this test needs to be updated. It should hopefully be pretty straightforward. 

Happy to hear you'd be willing to contribute a PR! We'd be happy to review it when you're done if this is the approach you want to take! Let us know if you have any questions there.

**Comment by ryan-brainforge** [comment]
Thanks @fivetran-avinash . 

I created a [PR](https://github.com/fivetran/dbt_shopify_source/pull/86) 
Please review.

**Comment by fivetran-jamie** [comment]
this is live in v0.12.1! many thanks @ryan-brainforge for the PR 😤
