### ISSUE TITLE
Field "state" in stg_shopify__customers

### ISSUE THREAD

**Issue by MartinGuindon** [fivetran/dbt_shopify_source#9]
The naming of the field `state` in the `stg_shopify__customers` is confusing as this name is normally related to the customer's address in this context.

Renaming the field to `account_state` would remove ambiguity.

I've discussed this change with Kristin and will issue a PR to fix this. Note this will be a breaking change and will require users of this package to update the reference in their models and/or BI tool.

**Comment by fivetran-kristin** [comment]
PR merged, thanks for the contribution!
